services:
    jenkins:
        build:
            context: ./jenkins
            dockerfile: Dockerfile
        ports:
            - "7080:8080"
        volumes:
            - "./jenkins/data:/var/jenkins_home"
        container_name: "jenkins_ci"
        restart: always