services:
    jenkins:
        build:
            context: ./src/jenkins
            dockerfile: Dockerfile
        ports:
            - "7080:8080"
        volumes:
            - "./src/jenkins/data:/var/jenkins_home"
        container_name: "jenkins_ci"
        restart: always
    grafana:
        build:
            context: ./src/grafana
            dockerfile: Dockerfile
        ports:
            - "7300:3000"
        volumes:
            - "./src/grafana/data:/var/lib/grafana"
        container_name: "grafana_ci"
        restart: always    
    prometheus:
        build:
            context: ./src/prometheus
            dockerfile: Dockerfile
        ports:
            - "7090:9090"
        volumes:
            - "./src/prometheus/data:/etc/prometheus"
        container_name: "prometheus_ci"
        restart: always